### ISSUE TITLE
Deleting a Teal source file results in an error

### ISSUE THREAD

**Issue by Lerg** [defold/extension-teal#5]
1. Create a teal file some.tl
2. Run project
3. Delete some.tl
4. Run project
5. Get an error
```
The file '/main/some.tl' could not be found.
```

**Comment by mikatuo** [comment]
That' a bummer. Tried Teal and accidentally noticed the same issue. Required Defold restart to make errors go away.

**Comment by vlaaad** [comment]
Fixed in https://github.com/defold/defold/commit/415b7a13d96c14dcce3239089b33736cfba4325e, check for the editor update.
